media_entity.bundle.*:
  type: mapping
  label: 'Media bundle'
  mapping:
    id:
      type: string
      label: 'Machine name'
    uuid:
      type: string
      label: 'UUID'
    name:
      type: label
      label: 'Name'
    type:
      type: label
      label: 'Type'
    description:
      type: text
      label: 'Description'
