media_entity.bundle.*:
  type: config_entity
  label: 'Media bundle'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    type:
      type: label
      label: 'Type'
    description:
      type: text
      label: 'Description'
