media_entity.bundle.*:
  type: config_entity
  label: 'Media bundle'
  mapping:
    id:
      type: string
      label: 'Machine name'
    label:
      type: label
      label: 'Label'
    description:
      type: text
      label: 'Description'
    type:
      type: string
      label: 'Type plugin ID'
    type_configuration:
      type: media_entity.bundle.type.[%type]
    field_map:
      type: mapping
      label: 'Field map'
