id: media.field_image
uuid: acc3afe4-9975-4cc0-a700-ef498406f5dc
name: field_image
entity_type: media
type: image
module: image
active: '1'
settings:
  uri_scheme: public
  default_image:
    fid: null
    alt: ''
    title: ''
    width: null
    height: null
locked: false
cardinality: 1
translatable: false
indexes: {  }
status: true
langcode: und
dependencies:
  module:
    - image
    - media_entity
